version: "3.8"

x-environ: &environ
  env_file: ./app/.env

x-base: &base
  <<: *environ
  build:
    context: .
    dockerfile: ./deploy/images/Dockerfile
  env_file: ./app/.env
  restart: on-failure
  image: koombea
  volumes:
    - ./app:/app

services:
  koombea-web:
    <<: *base
    container_name: koombea-web
    command: pipenv run gunicorn koombea.wsgi --bind 0:9020 --timeout 120 --log-level debug
    depends_on:
      - koombea-migrations
    ports:
      - 9020:9020
    restart: on-failure
    networks:
      - caddy-proxy
      - postgres

  koombea-migrations:
    <<: *base
    container_name: koombea-migrations
    command: pipenv run python manage.py migrate
    networks:
      - postgres

networks:
  postgres:
    name: postgres
    external: true

  caddy-proxy:
    name: caddy-proxy
    external: true
