# Generated by Django 4.2.6 on 2023-10-21 21:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('name', models.CharField(default='Page processing', max_length=255)),
                ('url', models.URLField()),
                (
                    'links',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=255), size=2
                        ),
                        null=True,
                        size=None
                    )
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('success', 'Success'), ('in progress', 'In progress'), ('failure', 'Failure')
                        ],
                        default='in progress',
                        max_length=11
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
            options={
                'db_table': 'page_content',
                'ordering': ['user', 'name'],
            },
        ),
    ]
